wandb_version: 1

dataset_name:
  desc: null
  value: 2_Cataracts-101
task:
  desc: null
  value: Phase_detection
model:
  desc: null
  value: CNN_RNN
num_classes:
  desc: null
  value: 10
num_clips:
  desc: null
  value: 4
clip_size:
  desc: null
  value: 20
step_size:
  desc: null
  value: 2
root_dir:
  desc: null
  value: /l/users/dana.mohamed
json_path:
  desc: null
  value: /home/dana.mohamed/MultiTask_Video_Data_Preprocessing/2_NEW_dataset_level_labels.json
checkpoint_path:
  desc: null
  value: /l/users/dana.mohamed/checkpoints/
learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 2
hidden_size:
  desc: null
  value: 512
bidirectional:
  desc: null
  value: false
criterion:
  desc: null
  value: CrossEntropyLoss
optimizer:
  desc: null
  value: Adam
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707853139.187293
    t:
      1:
      - 1
      - 5
      - 41
      - 48
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 48
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
